config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'homes#index'
  get 'homes/show'
  # get 'users/:id' => 'users#show'

  devise_for :users, controllers: {
        registrations: 'users/registrations'
  }

  devise_scope :user do
    # get "sign_in", :to => "users/sessions#new"
    # get "sign_out", :to => "users/sessions#destroy"
    get '/trainer/new' => 'trainers/registrations#new' ,as: :new_trainer
    post '/trainer' => 'trainers/registrations#create' ,as: :create_trainer
  end

  resources :users, only: %W(index show edit update destroy) do
    resources :trainer_evaluations
  end
  
  resources :trainer_evaluations
  resources :messages, :only => [:create]
  resources :rooms, :only => [:create, :show, :index]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable
  enum sex: { 男: 1, 女: 2, その他: 3}
  validates :name, presence: true, length: { maximum: 100 }
  validates :birthday, :sex, :tel, presence: true
  validates :email, uniqueness: true,  presence: true, length: { maximum: 200 },
            format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  mount_uploader :picture, PictureUploader

  has_one :trainer, inverse_of: :user
  accepts_nested_attributes_for :trainer
  has_many :trainer_evaluations, dependent: :destroy

  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy

  acts_as_taggable

  class << self
    def current_user=(user)
      Thread.current[:current_user] = user
    end

    def current_user
      Thread.current[:current_user]
    end
  end


  def get_current_room_id
    return if (!User.current_user)
    entries = self.entries.select do |entry| 
      targets = User.current_user.entries.select do |current_entry| 
        entry.room_id == current_entry.room_id
      end
      targets.length > 0
    end
    return entries.first.room_id if self.entries&.length > 0
  end

  def get_current_room
    return if (!User.current_user)
    entries = self.entries.select do |entry| 
      targets = User.current_user.entries.select do |current_entry| 
        entry.room_id == current_entry.room_id
      end
      targets.length > 0
    end
    return Room.find_by(id: self.entries.first.room_id) if self.entries&.length > 0
  end

  def get_current_DM_room_id
    return if (!User.current_user)
    entries = self.entries.select do |entry| 
      targets = User.current_user.entries.select do |current_entry| 
        entry.room_id == current_entry.room_id
      end
      targets.length > 0
    end
    return if self.entries&.length == 0
    room = Room.find_by(id: self.entries.first.room_id)
    return room.id if room.entries.length == 2
  end

  def get_current_DM_room
    return if (!User.current_user)
    entries = self.entries.select do |entry| 
      targets = User.current_user.entries.select do |current_entry| 
        entry.room_id == current_entry.room_id
      end
      targets.length > 0
    end
    return if self.entries&.length == 0
    room = Room.find_by(id: self.entries.first.room_id)
    return room if room.entries.length == 2
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   # if params[:trainer] == true
  #   #   Trainer.create()
  #   # end
  #   super
  # end
  
  def create
    super
    # user = User.new(configure_account_update_params)
    # user.save
    return
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  def configure_account_update_params #:picture_cache画像を保持する :remove_picture画像を削除する パラメーター
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :birthday, :sex, :email, :tel, :picture, :address,
                                      :infomation, :skype, :encrypted_password, :picture_cache, :remove_picture,
                                      trainer_attributes:[ :license, :experience, :belongs, :user_id]])
  end

  # アカウント編集後、プロフィール画面に移動する
  def after_update_path_for(resource)
    user_path(id: current_user.id)
  end


  # def after_update_path_for(resource)
  #   user_path(id: current_user.id)
  # end

  # def after_update_path_for(resource)
  #   user_path(current_user)
  # end

  # def after_update_path_for(resource)
  #   user_path(resource)
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

  def after_sign_up_path_for(resource)
    users_path
  end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    redirect_to users_path
  end

end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
# protect_from_forgery
before_action :set_user, only: [:edit, :update, :destroy] #MEMO: :show はユーザーがトレーナー詳細を確認するために外している
before_action :authenticate_user!, only: [:edit, :update, :destroy, :new, :create] #MEMO:ログイン外 トレーナー閲覧のみ可能
  def index
    @trainer_ids = Trainer.pluck(:user_id)
    @users = User.where(id: @trainer_ids)

    @user_search = @users.ransack(params[:q])
    @users = @user_search.result
    @tags = ActsAsTaggableOn::Tag.all
    @tag_search = @tags.ransack(params[:q])

    @tags = @tag_search.result
    if params[:tag_name]
      @users = @users.tagged_with("#{params[:tag_name]}")
    end
  end

  # def tag_cloud
  #   @tags = User.tag_counts_on(:tags)
  # end

  def show
    if Trainer.find_by(user_id: current_user.id).present?
      me_trainer = current_user
      @user = User.find_by(id: params[:id])
      @trainer = Trainer.find_by(user_id: @user.id)
      if @user == me_trainer
        # 自分がトレーナであり、ユーザーshowが自分のページであったら閲覧可能
      else
        redirect_to :root, notice: "ユーザー（トレーナーを除く）のみが閲覧できます"
      end
    else
      @user = User.find_by(id: params[:id])
      @trainer = Trainer.find_by(user_id: @user.id)
    end

    @user = User.find_by(id: params[:id])
    @trainer = Trainer.find_by(user_id: @user.id)
    @room = Room.new
    @entry = Entry.new
  end

  def edit
    # if current_user != @user
    #   redirect_to users_path
    # end
    unless @user.trainer.blank?
      @trainer = @user.trainer
    end
  end

  def update
    # if @user.id == current_user.id
      if @user.update(user_params)
        flash[:notice] = "情報を更新しました"
        redirect_to user_path(current_user.id)
      else
        flash[:alert] = "更新に失敗しました"
        render "edit"
      end
  end

  def destroy
      @user.destroy
      redirect_to root_path, notice:"アカウントを削除しました。ご利用頂きまして、ありがとうございました。"
  end
      # set_user.destroy
    # redirect_to user_path

private

  def user_params
    params.require(:user).permit(
      :name,
      :birthday,
      :sex,
      :email,
      :tel,
      :picture,
      :address,
      :infomation,
      :skype,
      :encrypted_password,
      :picture_cache,
      :remove_picture,
      :tag_list,
      trainer_attributes: [
        :id,
        :license,
        :experience,
        :belongs,
        :user_id,
      ]
    )
  end

  def set_user
    @user = User.find(params[:id])
    if current_user != @user
        redirect_to root_path,  alert: '違反行為です! 他のユーザーページにはいけません。'
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<%= form_with(model: @user,url: user_path(users_id: @user), method: :PATCH, local: true) do |f| %>
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <div class ="row">
        <section class="user-card col-md-12">
          <div class="user-card-img">
            <% if !!current_user %>
              <%= image_tag current_user.picture&.url , id: "avatar_picture_prev" %>
              <small><%= f.check_box :remove_picture %> 画像を削除</small>
            <% else %>
              <%= image_tag 'no_avatar.png', class: 'avatar_present_picture', id: "avatar_picture_prev" %>
              <%= f.hidden_field :picture_cache %>
            <% end %>
            <%= f.file_field :picture, id: 'post_picture' %>
          </div>
            <div class="user-card-content">
              <h1 class="user-card-title"><small><%= f.label :氏名 %></small><%= f.text_field :name, autofocus: true, autocomplete: "name" %></h1>
              <h3 class="text-center">基本情報</h3>
              <p class="user-card-text">
                <span>メールアドレス<%= f.email_field :email, autofocus: true, autocomplete: "email",class:"blank-content" %></span><br />
                <span>電話番号(ハイフン有り)<%= f.telephone_field :tel, autofocus: true, autocomplete: "tel",class:"blank-content"  %></span><br />
                <span>住所<%= f.text_field :address, autofocus: true, autocomplete: "address",class:"blank-content"  %></span><br />
                <span>Skype名<%= f.text_field :skype, autofocus: true, autocomplete: "skype",class:"blank-content"  %></span><br />
              <%= f.fields_for :trainer do |f| %>
                <span>資格<%= f.text_field :license, autofocus: true, autocomplete: "license",class:"blank-content"  %></span><br />
                <span>経験年数<%= f.text_field :experience, autofocus: true, autocomplete: "experience",class:"blank-content"  %></span><br />
                <span>所属先<%= f.text_field :belongs, autofocus: true, autocomplete: "belongs",class:"blank-content"  %></span><br />
              <% end %>
                <%# <span>得意とする指導内容<%= f.text_field :tag_list, value: @user.tag_list.join(','), class: "blank-content", placeholder: '例：腰痛予防、下半身強化等  *複数ある場合はカンマ（,)で区切ってください' %>
              <% unless @user.trainer.blank? %>
                <span>得意とする指導内容 *複数ある場合は、カンマ（、）で区切ってください<%= text_field_tag 'user[tag_list]', @user.tag_list.join('、'), :class => "blank-content" %></span>
              <% end %>
              </p>
              <h3 class="text-center">自己紹介</h3>
              <div class="user-card-content2">
                <span><%= f.text_area :infomation, autofocus: true, autocomplete: "infomation" %><br /></span>
              </div>
            </div>
              <div class="user-card-link">
                <div class="actions">
                  <%= f.submit "更新する" %>
                  <%= link_to 'パスワードを編集する', edit_user_registration_path , class:"btn-gradient-radius-user"%>
                </div>
              </div>
            </div>
        </section>
      </div>
    </div>
  </div>
</div>
<% end %>
<%# <%= link_to "退会する", user_path(@user.id), data: { confirm: "本当に退会しますか?" }, method: :DELETE, class:"session-input user-delete-button" %>
<%# <%= link_to "退会する", user_registration_path, data: { confirm: "本当に退会しますか?" }, method: :DELETE, class:"session-input user-delete-button" %>
<%# MEMO:DEMODAY用に退会できないよう設定 %>

app/views/users/index.html.erb
<div>
  <%= image_tag ('/FitNext-logo.png') , class:"trainer-index-container" %>
</div>

<div class="trainer-index-mask-container">
</div>

  <section class="index-section d-flex align-items-start">
		<div class="col-md-12">
    	<div class="card profile-card-3">
    	  <div class="background-block">
    		  <%# <img src="https://images.pexels.com/photos/459225/pexels-photo-459225.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" alt="profile-sample1" class="background"/> %>
          <%# <%= image_tag ('images/fitness-running.png') , class:"background" %>
          <%# , :alt => 'profile-sample1' %>
    		</div>
    		<div class="profile-thumb-block">
    		  <%# <img src="https://randomuser.me/api/portraits/men/41.jpg" alt="profile-image" class="profile"/> %>
          <%= image_tag ('images/masato-face.png') , class:"profile" %>
    		</div>
    		<div class="card-content">
          <h2>川北 雅冬<small>FItNext代表</small></h2>
          <h3>FitNextに登録しているトレーナー一覧画面です。</br>きっとあなたにぴったりな指導者がいるはずです。</br>毎日運動して、健康寿命を延ばしましょう。</h3>
          <%# <div class="icon-block"><a href="#"><i class="fa fa-facebook"></i></a><a href="#"> <i class="fa fa-twitter"></i></a><a href="#"> <i class="fa fa-google-plus"></i></a></div> %>
        </div>
      </div>
      <h1 class="mt-3 w-100 float-left text-center"><strong>トレーナー一覧</strong></h1>
          <div class ="col-md-12 mt-10">
            <%= search_form_for @user_search do |f| %>
              <%= f.label :name_cont, "トレーナー検索"%><br />
              <%= f.search_field :name_cont, class: "form-control", placeholder: "氏名で検索する" %>
              <%= f.label :tags_name_cont_any, "指導分野検索"%><br />
              <%= f.search_field :tags_name_cont_any, class: "form-control", placeholder: "指導分野で検索する" %>
              <%= f.submit "検索", :class => 'trainer_search_box text-center'  %>
            <% end %>
          </div>
          <h3 class="text-left">指導分野から選ぶ</h3>
          <div class ="col-md-12 mt-10 trainer-tag-container">
            <% @tags.each do |tag| %>
              <span class="badge badge-success trainer-tag"><%= link_to tag, users_path(tag_name: tag.name) %></span>
            <% end %>
          </div>
    </div>
  </section>

    <section class="index-section2">
    <% @users.each do |user| %>
        <div class="container">
          <div class="row">
            <div class="col-md-12 mt-10">
              <div class="card profile-card-5">
                <div class="card-img-block">
                  <%= image_tag user.picture&.url, class:"card-img-top picture_field img", alt:"Card image cap"%>
                </div>
                  <div class="card-body pt-0">
                    <h5 class="card-title trainer-card-title"><%= user.name %>トレーナー</h5>
                    <p class="card-text">
                    資格：<%= user.trainer.license %> | 経験：<%= user.trainer.experience %>年 | 所属：<%= user.trainer.belongs %>
                    </p>
                    <p class="card-text">
                    <%# 得意とする指導分野：<%= user.tag_list%>
                    <span>得意とする指導分野</span></br>
                    <% user.tag_list.each do |tag| %>
                    <span class="badge badge-success trainer-tag"><%= link_to tag, users_path(tag_name: tag) %></span>
                    <% end %>
                    </p>
                    <p class ="card-text">
                    自己紹介：<%= user.infomation %>
                    </p>
                    <%# <a href="#" class="btn btn-primary">Go somewhere</a> %>
                    <% if user_signed_in? && user.trainer.presence %>
                      <%= link_to '詳細ページ', user_path(user), class:"btn btn-primary" %>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          </div>
    <% end %>
  </section>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <div class ="row">
        <section class="user-card col-md-12">
          <%# <img class="user-card-img" src="http://webcreatorbox.com/sample/images/bear.jpg" alt=""> %>
          <div class="user-card-img">
            <%= image_tag @user.picture&.url %>
          </div>
            <div class="user-card-content">
              <h1 class="user-card-title"><%= @user.name %></h1>
              <h3 class="text-center">基本情報</h3>
              <p class="user-card-text">
                <span>性別: <%= @user.sex %></span></br>
                <span>生年月日: <%= @user.birthday %></span></br>
                <span>Skype名: <%= @user.skype %></span></br>
                  <% if @user.trainer.blank? %>
                    <span>メールアドレス: <%= @user.email %></span></br>
                    <span>電話番号: <%= @user.tel %></span></br>
                    <span>住所: <%= @user.address %></span></br>
                  <% end %>
                  <% unless @user.trainer.blank? %>
                    <span>資格：<%= @user.trainer.license %></span></br>
                    <span>経験年数：<%= @user.trainer.experience %>年</span></br>
                    <span>所属先：<%= @user.trainer.belongs %></span></br>
                    <%# <span>得意とする指導分野：<%= @user.tag_list %></span></br>
                    <span>得意とする指導分野</span></br>
                    <% @user.tag_list.each do |tag| %>
                    <span class="badge badge-success trainer-tag"><%= tag %></span>
                    <% end %>
                  <% end %>
              </p>
              <h3 class="text-center">自己紹介</h3>
              <div class="user-card-content2">
                <span><%= @user.infomation %></span>
              </div>
            </div>
              <div class="user-card-link">
                <% if @user.trainer.present? && @user != current_user %>
                  <%= link_to "指導を受ける(skypeログインページ)",'https://login.live.com/login.srf?wa=wsignin1.0&rpsnv=13&ct=1567423278&rver=7.1.6819.0&wp=MBI_SSL&wreply=https%3A%2F%2Flw.skype.com%2Flogin%2Foauth%2Fproxy%3Fclient_id%3D572381%26redirect_uri%3Dhttps%253A%252F%252Fweb.skype.com%252FAuth%252FPostHandler%26state%3D2383ec72-933d-42d4-b176-dfc30bc9400b%26site_name%3Dlw.skype.com&lc=1033&id=293290&mkt=ja-JP&psi=skype&lw=1&cobrandid=2befc4b5-19e3-46e8-8347-77317a16a5a5&client_flight=ReservedFlight33%2CReservedFlight67/', target:"_blank", class:"btn-gradient-radius-user" %>
                  <%= link_to '評価する', new_user_trainer_evaluation_path(user_id: @user, trainer_id: @user.trainer),class:"btn-gradient-radius-user" %></br>
                  <%= form_for @room do |f| %>
                    <%= f.hidden_field :user_id, value: @user.id %>
                    <%= f.submit "相談する" %>
                  <% end %>
                <% end %>
                <%if current_user.id == @user.id %>
                  <%= link_to 'プロフィールを編集する', edit_user_path(@user.id), class:"btn-gradient-radius-user" %>
                <% end %>
                <% if @user.try(:admin?) && ! (@user.id == @user) %>
                  <%= link_to '管理者ページ', "/admin", class:"btn-gradient-radius-user" %>
                <% end %>
                <%# FIXME:すでにメッセージがある場合、ユーザーがトレーナー詳細ページに訪れても”メッセージを確認する出ないようにする" %> 
                <%# MEMO:@userから＠current_userへ表示消える %>
                <% unless @current_user.trainer.blank? %>
                  <%= form_for @room do |f| %>
                    <%= f.hidden_field :user_id, value: @user.id %>
                    <%= f.submit "メッセージを確認する" %>
                  <% end %>
                <% end %>
              </div>
            </div>
        </section>
      </div>
    </div>
  </div>
</div>



<div class="trainer-evaluations-container">
  <div class="row">
    <div class="col-md-12">
      <% unless @user.trainer.blank? %>
      <h2 class="page-header">評価一覧</h2>
      <% end %>
        <section class="comment-list">
          <!-- First Comment -->
          <% unless @user.trainer.blank? %>
          <% @trainer.trainer_evaluations.each do |trainer_evaluation| %>
          <article class="row">
            <div class="col-md-12">
              <div class="panel panel-default arrow left">
                <div class="panel-body">
                  <header class="text-left">
                    <div class="comment-user">
                      <i><% if trainer_evaluation.user.picture_url %>
                        <%= image_tag trainer_evaluation.user.picture.url, class:"img-responsive-user"%>
                        <% end %>
                      </i><%= trainer_evaluation.user.name %>
                    </div>
                    <%# FIXME:投稿者の名前を表示 %>
                    <%# <time class="comment-date" datetime="16-12-2014 01:05"><i class="fa fa-clock-o"></i> Dec 16, 2014</time> %>
                  </header>
                  <div class="comment-post">
                    <p class="trainer-evaluations-font">
                      <%# 「user_id」：<%= trainer_evaluation.user.name %>
                      「楽しさ」：<%= trainer_evaluation.fun_rate %><br />
                      「わかりやすさ」：<%= trainer_evaluation.understandable_rate %><br />
                      「丁寧さ」：<%= trainer_evaluation.politeness_rate %><br />
                      「優しさ」：<%= trainer_evaluation.kindness_rate %><br />
                      「熱心さ」：<%= trainer_evaluation.passion_rate %><br />
                      「自由記述」：<%= trainer_evaluation.content %><br />
                    </p>
                  </div>
                  <%# <p class="text-right"><a href="#" class="btn btn-default btn-sm"><i class="fa fa-reply"></i> reply</a></p> %>
                </div>
              </div>
            </div>
          </article>
          <% end %>
          <% end %>
        </section>
    </div>
  </div>
</div>