config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'homes#index'
  get 'homes/show'
  # get 'users/:id' => 'users#show'

  devise_for :users, controllers: {
        registrations: 'users/registrations'
  }

  devise_scope :user do
    # get "sign_in", :to => "users/sessions#new"
    # get "sign_out", :to => "users/sessions#destroy"
    get '/trainer/new' => 'trainers/registrations#new' ,as: :new_trainer
    post '/trainer' => 'trainers/registrations#create' ,as: :create_trainer
  end

  resources :users, only: %W(index show edit update destroy) do
    resources :trainer_evaluations
  end
  
  resources :trainer_evaluations
  resources :messages, :only => [:create]
  resources :rooms, :only => [:create, :show, :index]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="noIE" lang="en-US">
  <head>
    <title>FitNext Fitness×NextStage</title>
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>
			<meta name="viewport" content="width=device-width, initial-scale=1.0" />
			<link href="https://use.fontawesome.com/releases/v5.0.10/css/all.css" rel="stylesheet">
			<%# FIXME:上記リンク入れずに実装できる方法を模索 %>
      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
      <%= notice %>
			<%= alert %>
			<%= favicon_link_tag('fitnext.ico') %>
			<!-- User Heat Tag -->
				<script type="text/javascript">
				(function(add, cla){window['UserHeatTag']=cla;window[cla]=window[cla]||function(){(window[cla].q=window[cla].q||[]).push(arguments)},window[cla].l=1*new Date();var ul=document.createElement('script');var tag = document.getElementsByTagName('script')[0];ul.async=1;ul.src=add;tag.parentNode.insertBefore(ul,tag);})('//uh.nakanohito.jp/uhj2/uh.js', '_uhtracker');_uhtracker({id:'uhBMuYQ4EL'});
				</script>
			<!-- End User Heat Tag -->
			<!-- Google Tag Manager -->
			<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
			new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
			j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
			'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
			})(window,document,'script','dataLayer','GTM-T3DJSX9');</script>
			<!-- End Google Tag Manager -->
  </head>
	<body>
	<!-- Google Tag Manager (noscript) -->
	<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-T3DJSX9"
	height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
	<!-- End Google Tag Manager (noscript) -->
		<header class="top-header">
			<div class="container">
				<div class="row">
					<div class="header-logo">
							<h1 class="logo"><%= link_to 'FitNext', root_path %></h1>
							<%= link_to 'Fitness×NextStage', root_path, class:"logo-mini" %>
					</div>
					<div class="header-logo-right">
						<nav class="navbar navbar-default">
								<div class="container-fluid nav-bar">
								<!-- Brand and toggle get grouped for better mobile display -->
									<div class="navbar-header">
									</div>
									<!-- Collect the nav links, forms, and other content for toggling -->
									<div class="" id="">
										<ul class="nav navbar-nav navbar-right">
											<% if user_signed_in? %>
												<%= link_to '概要', homes_show_path, class:"btn-border-bottom" %>
												<%= link_to 'トレーナー一覧', users_path, class:"btn-border-bottom" %>
												<%= link_to 'マイページ', user_path(current_user), class:"btn-border-bottom" %>
												<%= link_to 'ログアウト', destroy_user_session_path, method: :get, class:"btn-border-bottom header-signout" %>
											<% else %>
												<%= link_to '概要', homes_show_path, class:"btn-border-bottom hidden-in-md" %>
												<%= link_to '会員登録', new_user_registration_path, class:"btn-border-bottom" %>
												<%= link_to 'トレーナー登録',  new_trainer_path, class:"btn-border-bottom" %>
												<%= link_to 'ログイン', new_user_session_path, class:"btn-border-bottom" %>
												<%= link_to 'トレーナー一覧', users_path, class:"btn-border-bottom" %>
											<% end %>
										</ul>
									<div>
									</ul><!-- /navbar-collapse -->
								</div><!-- / .container-fluid -->
						</nav>
					</div>
				</div>
			</div>
		</header>
    <%= yield %>
  </body>
</html>